/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.individual.lp;

import java.awt.Color;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author user
 */
public class Tela1 extends javax.swing.JFrame {
    // Estatisticas(Min,Avg e Max)
    Double valueMaxCpu = 0.0;
    Double valueMinCpu = 1000000.0;
    Double valueMedCpu;
    Double somaCpu = 0.0;
    Double valueMaxDisk = 0.0;
    Double valueMinDisk = 10000000.0;
    Double valueMedDisk;
    Double somaDisk = 0.0;
    Double valueMaxMem = 0.0;
    Double valueMinMem = 10000000.0;
    Double valueMedMem;
    Double somaMem = 0.0;
    Integer contador = 1;

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pbCpu = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pbDisk = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        pbMemoria = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCpuMin = new javax.swing.JLabel();
        lbCpuMed = new javax.swing.JLabel();
        lbCpuMax = new javax.swing.JLabel();
        lb77 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbDiskMax = new javax.swing.JLabel();
        lbDiskMed = new javax.swing.JLabel();
        lbDiskMin = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbMemMin = new javax.swing.JLabel();
        lbMemMed = new javax.swing.JLabel();
        lbMemMax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DISCO");

        pbCpu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pbCpu.setPreferredSize(new java.awt.Dimension(146, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CPU");

        pbDisk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pbDisk.setPreferredSize(new java.awt.Dimension(146, 25));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEMÓRIA");

        pbMemoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pbMemoria.setPreferredSize(new java.awt.Dimension(146, 25));

        jButton1.setText("Fazer leitura dos dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Minimo");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Média");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Maximo");

        lbCpuMin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCpuMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpuMin.setText("???");

        lbCpuMed.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCpuMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpuMed.setText("???");

        lbCpuMax.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCpuMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpuMax.setText("???");

        lb77.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb77.setText("Minimo");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Média");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Maximo");

        lbDiskMax.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbDiskMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiskMax.setText("???");

        lbDiskMed.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbDiskMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiskMed.setText("???");

        lbDiskMin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbDiskMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiskMin.setText("???");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Minimo");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Média");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Maximo");

        lbMemMin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbMemMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMemMin.setText("???");

        lbMemMed.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbMemMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMemMed.setText("???");

        lbMemMax.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbMemMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMemMax.setText("???");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCpuMin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCpuMed, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCpuMax, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbDisk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDiskMin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDiskMed, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDiskMax, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMemMin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMemMed, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbMemMax, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lb77, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpuMin)
                    .addComponent(lbCpuMed)
                    .addComponent(lbCpuMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbDisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb77)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiskMin)
                    .addComponent(lbDiskMed)
                    .addComponent(lbDiskMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMemMin)
                    .addComponent(lbMemMed)
                    .addComponent(lbMemMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Variaveis
        Double valorCpu = ThreadLocalRandom.current().nextDouble(2, 5);
        Double valorDisk = ThreadLocalRandom.current().nextDouble(240, 1000);
        Double valorMem = ThreadLocalRandom.current().nextDouble(2, 8);
        
        // Colocando valores maximos de referência
        pbCpu.setMaximum(5);
        pbDisk.setMaximum(1000);
        pbMemoria.setMaximum(8);
        
        // Configurando String na barra
        pbCpu.setStringPainted(true);
        pbCpu.setForeground(Color.black);
        pbDisk.setStringPainted(true);
        pbDisk.setForeground(Color.black);
        pbMemoria.setStringPainted(true);
        pbMemoria.setForeground(Color.black);
        
        // Colocando o valor na String da barra
        pbCpu.setString(String.format("%.2f GHz", valorCpu));
        pbDisk.setString(String.format("%.2f GB", valorDisk));
        pbMemoria.setString(String.format("%.2f GB", valorMem));
        
        // Colocando os valores gerados nas barras
        pbCpu.setValue(valorCpu.intValue());
        pbDisk.setValue(valorDisk.intValue());
        pbMemoria.setValue(valorMem.intValue());
        
        // Atualizar Min, Max e Media - CPU
        if (valorCpu > valueMaxCpu) {
            valueMaxCpu = valorCpu;
            lbCpuMax.setText(String.format("%.2f", valorCpu));
        }
        if (valorCpu < valueMinCpu) {
            valueMinCpu = valorCpu;
            lbCpuMin.setText(String.format("%.2f", valorCpu));
        }
        
        somaCpu += valorCpu;
        valueMedCpu = somaCpu / contador;
        
        lbCpuMed.setText(String.format("%.2f", valueMedCpu));
        
        // Atualizar Min, Max e Media - Disco
        if (valorDisk > valueMaxDisk) {
            valueMaxDisk = valorDisk;
            lbDiskMax.setText(String.format("%.2f", valorDisk));
        }
        if (valorDisk < valueMinDisk) {
            valueMinDisk = valorDisk;
            lbDiskMin.setText(String.format("%.2f", valorDisk));
        }
        
        somaDisk += valorDisk;
        valueMedDisk = somaDisk / contador;
        
        lbDiskMed.setText(String.format("%.2f", valueMedDisk));
        
        // Atualizar Min, Max e Media - Memoria
        if (valorMem > valueMaxMem) {
            valueMaxMem = valorMem;
            lbMemMax.setText(String.format("%.2f", valorMem));
        }
        if (valorMem < valueMinMem) {
            valueMinMem = valorMem;
            lbMemMin.setText(String.format("%.2f", valorMem));
        }
        
        somaMem += valorMem;
        valueMedMem = somaMem / contador;
        
        lbMemMed.setText(String.format("%.2f", valueMedMem));
        
        contador++;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb77;
    private javax.swing.JLabel lbCpuMax;
    private javax.swing.JLabel lbCpuMed;
    private javax.swing.JLabel lbCpuMin;
    private javax.swing.JLabel lbDiskMax;
    private javax.swing.JLabel lbDiskMed;
    private javax.swing.JLabel lbDiskMin;
    private javax.swing.JLabel lbMemMax;
    private javax.swing.JLabel lbMemMed;
    private javax.swing.JLabel lbMemMin;
    private javax.swing.JProgressBar pbCpu;
    private javax.swing.JProgressBar pbDisk;
    private javax.swing.JProgressBar pbMemoria;
    // End of variables declaration//GEN-END:variables
}
